In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

data =pd.read_excel("/content/drive/MyDrive/Bootcamp/NetflixOriginals.xlsx")


data['IMDB Score'] = data['IMDB Score'].astype('float')

In [3]:
data

,Title,Genre,Premiere,Runtime,IMDB Score,Language
0,Enter the Anime,Documentary,"August 5, 2019",58,2.5,English/Japanese
1,Dark Forces,Thriller,"August 21, 2020",81,2.6,Spanish
2,The App,Science fiction/Drama,"December 26, 2019",79,2.6,Italian
3,The Open House,Horror thriller,"January 19, 2018",94,3.2,English
4,Kaali Khuhi,Mystery,"October 30, 2020",90,3.4,Hindi
...,...,...,...,...,...,...
579,Taylor Swift: Reputation Stadium Tour,Concert Film,"December 31, 2018",125,8.4,English
580,Winter on Fire: Ukraine's Fight for Freedom,Documentary,"October 9, 2015",91,8.4,English/Ukranian/Russian
581,Springsteen on Broadway,One-man show,"December 16, 2018",153,8.5,English
582,Emicida: AmarElo - It's All For Yesterday,Documentary,"December 8, 2020",89,8.6,Portuguese
583,David Attenborough: A Life on Our Planet,Documentary,"October 4, 2020",83,9.0,English

In [7]:
data.groupby(["Language"])["Genre"].value_counts(sort=True).groupby(level=0).head(1)

Language                    Genre
Bengali                     Documentary                1
Dutch                       Crime drama                1
English                     Documentary              120
English/Akan                War drama                  1
English/Arabic              Documentary                1
English/Hindi               Documentary                2
English/Japanese            Crime drama                1
English/Korean              Action-adventure           1
English/Mandarin            Documentary                2
English/Russian             Documentary                1
English/Spanish             Documentary                5
English/Swedish             Documentary                1
English/Taiwanese/Mandarin  Drama                      1
English/Ukranian/Russian    Documentary                1
Filipino                    Drama                      1
French                      Documentary                6
Georgian                    Documentary                1
German                      Drama                      1
Hindi                       Drama                     13
Indonesian                  Drama                      3
Italian                     Drama                      4
Japanese                    Anime/Science fiction      2
Khmer/English/French        Drama                      1
Korean                      Drama                      2
Malay                       Action comedy              1
Marathi                     Drama                      2
Norwegian                   Horror                     1
Polish                      Horror                     1
Portuguese                  Comedy                     6
Spanish                     Documentary                8
Spanish/Basque              Black comedy               1
Spanish/Catalan             Documentary                1
Spanish/English             Documentary                1
Swedish                     Thriller                   1
Tamil                       Drama                      1
Thai                        Documentary                1
Thia/English                Documentary                1
Turkish                     Comedy                     2
Name: Genre, dtype: int64