In [53]:
#Dersler={1:"Matematik",2:"Geometri",3:"Fen Bilgisi",4:"Kimya",5:"Fizik"}
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

def Not_Araligi(puan):
  Harf_Notu=""
  Gecti_Mi=""
  if puan<45 and puan>=0:
    Harf_Notu="E"
    Gecti_Mi="Kalmıştır"
  elif puan<55 and puan>=45:
    Harf_Notu="D"
    Gecti_Mi="Geçmiştir"
  elif puan<70 and puan>=55:
    Harf_Notu="C"
    Gecti_Mi="Geçmiştir"
  elif puan<85 and puan>=70:
    Harf_Notu="B"
    Gecti_Mi="Geçmiştir"
  elif puan<95 and puan>=85:
    Harf_Notu="A"
    Gecti_Mi="Geçmiştir"
  elif puan<100 and puan>=95:
    Harf_Notu="A+"
    Gecti_Mi="Geçmiştir"
  return Harf_Notu,Gecti_Mi

In [54]:
gecti_kaldi_df=pd.DataFrame(columns=["ID","Ad","Soyad","Ders","Puan","Harf Notu","Durumu"])
Cebir1=dict()
def Kayit(id,ad,soyad,ders,puan):
  Harf_Notu,Gecti_Mi=Not_Araligi(puan)
  Cebir1[id]=[ad,soyad,ders,puan]
  gecti_kaldi_df.loc[-1]=[id,ad,soyad,ders,puan,Harf_Notu,Gecti_Mi]
  gecti_kaldi_df.reset_index(drop=True,inplace=True)
  print(ad,soyad,Harf_Notu,"ile",Gecti_Mi,".")
  return gecti_kaldi_df

def Ogrenci_Kaydi():
    a=str(input("Öğrencinin numarasını giriniz: "))
    b=str(input("Öğrencinin adını giriniz: "))
    c=str(input("Öğrencinin soyadını giriniz: "))
    d=str(input("Eklenecek dersi giriniz: "))
    e=float(input("Dersin Notunu Giriniz: "))
    Kayit(a,b,c,d,e)
    print("Kaydınız başarıyla tamamlanmıştır.")
    #with open("notlar.txt","a",encoding="utf-8") as file:

In [55]:
Kayit(11,"Ömer","Tekin","Fizik",75)
Kayit(12,"Tamer","Tekin","Matematik",65)
Kayit(23,"Büşra","Köksal","Matematik",70)
Kayit(34,"Zeynep","Akkoç","Fizik",90)
Kayit(54,"Tuana","Kurşun","Kimya",65)
Kayit(10,"Zeynep","Aslan","Türkçe",65)
Kayit(37,"Beyza","Köksal","Kimya",65)

Ömer Tekin B ile Geçmiştir .
Tamer Tekin C ile Geçmiştir .
Büşra Köksal B ile Geçmiştir .
Zeynep Akkoç A ile Geçmiştir .
Tuana Kurşun C ile Geçmiştir .
Zeynep Aslan C ile Geçmiştir .
Beyza Köksal C ile Geçmiştir .

   ID      Ad   Soyad       Ders Puan Harf Notu     Durumu
0  11    Ömer   Tekin      Fizik   75         B  Geçmiştir
1  12   Tamer   Tekin  Matematik   65         C  Geçmiştir
2  23   Büşra  Köksal  Matematik   70         B  Geçmiştir
3  34  Zeynep   Akkoç      Fizik   90         A  Geçmiştir
4  54   Tuana  Kurşun      Kimya   65         C  Geçmiştir
5  10  Zeynep   Aslan     Türkçe   65         C  Geçmiştir
6  37   Beyza  Köksal      Kimya   65         C  Geçmiştir

In [56]:
while True:
  print("Yapılacak işlemler \n 1: Yeni öğrenci kaydı \n 2: Öğrenci not döküm tablosunu görüntüleme \n Sistemden çıkış")
  x = input("Yapılacak işlemi seçiniz: ")
  if (int(x)==1):
    Ogrenci_Kaydi()
  elif (int(x)==2):
    print(gecti_kaldi_df)
  elif (int(x)==3):
    print("Sistemden çıktınız.")
    break
  else:
    print("Hatalı işlem!!!")

Yapılacak işlemler
 1: Yeni öğrenci kaydı
 2: Öğrenci not döküm tablosunu görüntüleme
 Sistemden çıkış
Yapılacak işlemi seçiniz: 1
Öğrencinin numarasını giriniz: 44
Öğrencinin adını giriniz: Selin
Öğrencinin soyadını giriniz: Yılmaz
Eklenecek dersi giriniz: Fizik
Dersin Notunu Giriniz: 58
Selin Yılmaz C ile Geçmiştir .
Kaydınız başarıyla tamamlanmıştır.
Yapılacak işlemler
 1: Yeni öğrenci kaydı
 2: Öğrenci not döküm tablosunu görüntüleme
 Sistemden çıkış
Yapılacak işlemi seçiniz: 2
   ID      Ad   Soyad       Ders  Puan Harf Notu     Durumu
0  11    Ömer   Tekin      Fizik    75         B  Geçmiştir
1  12   Tamer   Tekin  Matematik    65         C  Geçmiştir
2  23   Büşra  Köksal  Matematik    70         B  Geçmiştir
3  34  Zeynep   Akkoç      Fizik    90         A  Geçmiştir
4  54   Tuana  Kurşun      Kimya    65         C  Geçmiştir
5  10  Zeynep   Aslan     Türkçe    65         C  Geçmiştir
6  37   Beyza  Köksal      Kimya    65         C  Geçmiştir
7  44   Selin  Yılmaz      Fizik  58.0         C  Geçmiştir
Yapılacak işlemler
 1: Yeni öğrenci kaydı
 2: Öğrenci not döküm tablosunu görüntüleme
 Sistemden çıkış
Yapılacak işlemi seçiniz: 3
Sistemden çıktınız.

In [57]:
gecti_kaldi_df.to_excel("sonuçlar.xlsx")